version: "3.8"
services:
    database:
        image: mongo:latest
        container_name: chatterer-database
        environment:
            - MONGO_INITDB_ROOT_USERNAME=chatterer
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes: 
            - mongodb_data_container:/data/db
        ports: 
            - 27017:27017 
    frontend:
        container_name: "chatterer-frontend"
        build:
            context: chatterer-client/
            dockerfile: Dockerfile
        volumes:
            - './chatterer-client:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    backend:
        image: chattererserver
        build:
            context: .
            dockerfile: Chatterer-server/Dockerfile
        ports:
            - 5000:80
volumes:
    mongodb_data_container: